package intermediate.recursion_8;

public class FindKthElementGoogle_7 { // refer 21._Jun22_Recursion___2.pdf

	public static void main(String[] args) {
		// This Question was Asked in Google.
		// Every element is generated by replacing all elements of previous row
		// 0->{0,1}, 1->{1,0}. Given N & k, find K'th element in N'th row.
		System.out.println(find(4, 4));
	}

	public static int find(int N, int K) {
		if (K == 0) {
			return 0;
		}
		int parent = find(N - 1, K / 2);
		if (K % 2 == 0) {
			return parent;
		} else {
			return 1 - parent;
		}
	}

}
